import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Leon's Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div>

       <h1>hello, i'm leon, this is my page</h1>

       <section>

         <h2>Things I Like</h2>
         <ul>
           <li>Food</li>
           <li>Snow</li>
           <li>Winter</li>
           <li>Robots</li>
           <li>Building</li>
           <li>Folding/Cutting</li>
           <li>Crafts</li>
         </ul>

       </section>

       <section>
         <h2>What this nonsense is about:</h2>

         <p>
           to be determined
         </p>

         <ul>
           <li></li>
         </ul>

       </section>
     </div>
    </>
  )
}
