import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Leon's Website Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div>
       hello, i'm leon, this is my website
     </div>
    </>
  )
}
